services:
  db:
    image: postgres:15
    hostname: db
    environment:
      POSTGRES_USER: marksuser
      POSTGRES_PASSWORD: markspass
      POSTGRES_DB: marksdb
    # Pre-seed script is required as a volume to load mock database
    # Data inside the container is lost on restart unless you persist it with a volume.
    ports:
      - "5432:5432"
    volumes:
      - my_db_volume:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: 5000:5000
    depends_on:
      - db

  frontend:
    # TODO: you will need to add to this

      ports: 5173:8080
      depends_on:
      - backend

  automark:
    build: ./automark
    depends_on:
      - backend
      - db
    profiles:
      - debug
